name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # Every Sunday at 6:15 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display Event Name
        run: echo "Event that triggered the workflow: ${{ github.event_name }}"

      - name: Display Branch Name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Base branch: ${{ github.base_ref }}"
            echo "PR branch: ${{ github.head_ref }}"
          else
            echo "Branch: ${{ github.ref_name }}"
          fi

      - name: List All Files in Repository
        run: ls -R
